{
 "title": "FOSSology Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Unique Hash",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "count",
   "valueName": "avg",
   "targets": [
    { "expr": "unique_hash" }
   ]
  },
  {
   "title": "Unique Hash",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "unique_hash" }
   ]
  },
  {
   "title": "agent run",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    { "expr": "agent_run" }
   ]
  },
  {
   "title": "Number of Project  per instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_of_project{server_instance=\"server1\"}"
    },
    {
     "expr": "num_of_project{server_instance=\"server2\"}"
    }
   ]
  }
 ]
}