{
 "title": "FOSSY_DASH",
 "time": { "from": "2020-06-04T04:49:09.000Z", "to": "now" },
 "panels": [
  {
   "title": "number_file_uploads",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "number_of_file_uploads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pfile_count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pfile_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of User",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "number_of_users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent_count per instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agents_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "agent_count per type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agents_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job_count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "job_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}